apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: vuln-remediation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:5.0.9
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  namespace: vuln-remediation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd:2.4.49