apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:12.0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-vulnerable
  template:
    metadata:
      labels:
        app: node-vulnerable
    spec:
      containers:
      - name: app
        image: node:12.0.0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-vulnerable
  template:
    metadata:
      labels:
        app: java-vulnerable
    spec:
      containers:
      - name: app
        image: openjdk:8u0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-vulnerable
  template:
    metadata:
      labels:
        app: python-vulnerable
    spec:
      containers:
      - name: app
        image: python:2.7.0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-vulnerable
  template:
    metadata:
      labels:
        app: ubuntu-vulnerable
    spec:
      containers:
      - name: app
        image: ubuntu:16.04
