import os
import glob
import uuid
from github import Github
from github import Auth

def create_remediation_pr(repo_name, manifests_dir="manifests/remediated"):
    token = os.getenv("GITHUB_TOKEN")
    if not token:
        raise ValueError("The GITHUB_TOKEN environment variable is not set.")

    auth = Auth.Token(token)
    g = Github(auth=auth)
    repo = g.get_repo(repo_name)

    base_branch = repo.default_branch
    base_ref = repo.get_git_ref(f"heads/{base_branch}")

    branch_name = f"remediation/update-{uuid.uuid4().hex[:8]}"
    repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=base_ref.object.sha)

    commit_message = "Automated vulnerability remediation via AI Agent"
    files_changed = False

    yaml_files = glob.glob(os.path.join(manifests_dir, "*.yaml"))
    
    for filepath in yaml_files:
        with open(filepath, 'r') as file:
            content = file.read()
        
        file_name = os.path.basename(filepath)
        target_path = f"manifests/base/{file_name}" 
        
        try:
            contents = repo.get_contents(target_path, ref=base_branch)
            repo.update_file(contents.path, commit_message, content, contents.sha, branch=branch_name)
        except Exception:
            repo.create_file(target_path, commit_message, content, branch=branch_name)
        
        files_changed = True

    if not files_changed:
        print("No .yaml files found in the directory. Aborting.")
        return None

    pr_title = "Automated Vulnerability Remediation Updates"
    pr_body = (
        "This Pull Request contains automated remediations for container image vulnerabilities, "
        "generated by the AI Agent.\n\n"
        "Please review the changes in the manifests before merging this PR."
    )
    
    pr = repo.create_pull(
        title=pr_title,
        body=pr_body,
        head=branch_name,
        base=base_branch
    )
    
    return pr.html_url